In [24]:
import time

# Using manual Python Loops
# Marks dataset
marks = [
    [78, 91, 68, 54],
    [82, 47, 60, 78],
    [97, 58, 62, 50],
    [50, 63, 92, 75],
    [79, 63, 42, 61]
]
print("Original Marks : \n", marks)

# Pre-computed means and stds for each column (subject)
mean = [77.2, 64.4, 64.8, 63.6]
std  = [15.22, 14.52, 16.12, 11.14]
print("\nMean (per subject):", mean)
print("Std Deviation (per subject):", std)

# Start timer
start_time = time.time()

# Normalization using loops
normalized_loops = []
for i in range(len(marks)):           # loop over students (rows)
    row = []
    for j in range(len(marks[0])):    # loop over subjects (columns)
        z = (marks[i][j] - mean[j]) / std[j]
        row.append(z)
    normalized_loops.append(row)

end_time = time.time()

print("\nZ-values (Normalized with loops):\n", normalized_loops)
print("\nTime taken using loops: {:.8f} seconds".format(end_time - start_time))

Original Marks : 
 [[78, 91, 68, 54], [82, 47, 60, 78], [97, 58, 62, 50], [50, 63, 92, 75], [79, 63, 42, 61]]

Mean (per subject): [77.2, 64.4, 64.8, 63.6]
Std Deviation (per subject): [15.22, 14.52, 16.12, 11.14]

Z-values (Normalized with loops):
 [[0.052562417871221886, 1.8319559228650135, 0.1985111662531019, -0.8617594254937164], [0.31537450722733223, -1.198347107438017, -0.2977667493796524, 1.2926391382405744], [1.3009198423127462, -0.44077134986225935, -0.17369727047146383, -1.220825852782765], [-1.7871222076215507, -0.09641873278236954, 1.687344913151365, 1.023339317773788], [0.11826544021024948, -0.09641873278236954, -1.4143920595533497, -0.23339317773788162]]

Time taken using loops: 0.00009799 seconds


In [25]:
import numpy as np
import time

# Using NumPy (Vectorization)

# sample dataset (5 students × 4 subjects)
np.random.seed(42)                               # for reproducibility
marks = np.random.randint(40, 100, size=(5, 4))  # marks between 40 and 100
print("Original Marks:\n", marks)

# mean & standard deviation (per subject/column)
mean = marks.mean(axis=0)                        # mean per subject
std = marks.std(axis=0)                          # std per subject
print("\nMean (per subject):", mean)
print("Std Deviation (per subject):", std)

# start timer
start_time = time.time()

# Normalize the dataset using vectorization (Z-score normalization)
normalized_marks = (marks - mean) / std

end_time = time.time()

print("\nNormalized Marks (Z-scores):\n", normalized_marks)
print("\nTime taken using NumPy vectorization: {:.8f} seconds".format(end_time - start_time))

Original Marks:
 [[78 91 68 54]
 [82 47 60 78]
 [97 58 62 50]
 [50 63 92 75]
 [79 63 42 61]]

Mean (per subject): [77.2 64.4 64.8 63.6]
Std Deviation (per subject): [15.22366579 14.52721584 16.12947612 11.14629983]

Normalized Marks (Z-scores):
 [[ 0.05254976  1.83104597  0.19839454 -0.86127236]
 [ 0.31529857 -1.19775187 -0.29759181  1.29190854]
 [ 1.30060659 -0.44055241 -0.17359522 -1.22013585]
 [-1.78669188 -0.09637084  1.68635359  1.02276093]
 [ 0.11823696 -0.09637084 -1.4135611  -0.23326127]]

Time taken using NumPy vectorization: 0.00004101 seconds
