In [1]:
import numpy as np
import time

In [2]:
#q1 Create a NumPy array with values from 10 to 100 and print its shape.

print("Creating NumPy array from 10 to 100")
arr1 = np.arange(10,101)
print(arr1)
print(f"Shape {arr1.shape}")
print(f"Size  {arr1.size}")

Creating NumPy array from 10 to 100
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Shape (91,)
Size  91


In [3]:
#q2 Compare the time taken to multiply two Python lists vs. NumPy arrays.

size = 1000000
list1 = list(range(size))
list2 = list(range(size, 2*size))

arr2_1 = np.array(list1)
arr2_2 = np.array(list2)

start_time1 = time.time()
list_result = [a*b for a, b in zip(list1,list2)]
end_time1 = time.time() 
list_time =end_time1 - start_time1

#NumPy arrya Multiplication
start_time2 = time.time()
numpy_result = arr2_1 * arr2_2
end_time2 = time.time()
numpy_time = end_time2 - start_time2
print(f"Time taken by List : {list_time:.4f} seconds")
print(f"Time taken by NumPy : {numpy_time:.4f} seconds")
print(f"List takes {list_time/numpy_time:.2f}x more time than NumPy")
print(arr2_1.nbytes,"Bytes occupied by arr2_1")

Time taken by List : 0.2582 seconds
Time taken by NumPy : 0.0105 seconds
List takes 24.53x more time than NumPy
8000000 Bytes occupied by arr2_1


In [4]:
#Q3 Find the memory size of a NumPy array with 1 million elements.

arr3 = np.arange(1000000)
print(arr3.nbytes/(1024**2),"MB")
arr3_int32 = arr3.astype(np.int32)
print(arr3_int32.nbytes/(1024**2),"MB")
arr3_int16 = arr3.astype(np.int16)
print(arr3_int16.nbytes/(1024**2),"MB")

7.62939453125 MB
3.814697265625 MB
1.9073486328125 MB


In [5]:
#Q4 Create a 3×3 array of random numbers and find its mean, median, and std.

arr4 = np.random.rand(3,3)
print("Array:\n",arr4)
mean_val1 = np.mean(arr4)
median_val1 = np.median(arr4)
std_val1 =np.std(arr4)
print(f"The mean is: {mean_val1} \nThe median value is: {median_val1}\n")

Array:
 [[0.84134167 0.24594009 0.05627359]
 [0.96949006 0.97162992 0.51543335]
 [0.44050721 0.25921524 0.16645978]]
The mean is: 0.49625454685873804 
The median value is: 0.4405072094206406



In [6]:
#Q5 Reshape a 1D array of size 12 into a 3×4 matrix.

arr5_1 = np.array([2,5,7,9,2,4,56,8,7,3,7,6])
print(f"Length of arr5_1 : {len(arr5_1)}")
arr5_2 = np.full((3,4),arr5_1[3])
arr5_3 = arr5_1.reshape(3,4)
print(arr5_2)
arr5_3

Length of arr5_1 : 12
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


array([[ 2,  5,  7,  9],
       [ 2,  4, 56,  8],
       [ 7,  3,  7,  6]])

In [7]:
#Q6 Use boolean masking to extract all values > 50 from an array.

arr6_1 = np.array([44,6,1,3,76,24,754,214,66,33,66,7,8,888,])
mask = arr6_1 > 50
print(arr6_1[mask])

[ 76 754 214  66  66 888]


In [8]:
#Q7 Create a 5×5 identity matrix and replace the diagonal with 7.

arr7_1 = np.eye(5)
print(f" original marrix :\n {arr7_1} \n")
arr7_3 =arr7_1.copy()
np.fill_diagonal(arr7_3 , 7)
print(arr7_3)

 original marrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]


In [9]:
#Q8 Generate an array of 50 random integers between 1–100 and find the unique values.

random_int = np.random.randint(1,100, size = 50)
print(random_int)
unique_values = np.unique(random_int)
print(f"unique values are {unique_values}")

[86  4 27 22 97  4 62 80 50 80  7 71 93 47 88 81 16 28 81 71 53 98 63 50
 87 16 29 95 46 73 61 12 25  7 84 32 99 13 36 17 84 16 85 41 33 78 42 95
 28 21]
unique values are [ 4  7 12 13 16 17 21 22 25 27 28 29 32 33 36 41 42 46 47 50 53 61 62 63
 71 73 78 80 81 84 85 86 87 88 93 95 97 98 99]


In [10]:
#Q9 Create two arrays and create their dot product and cross product 

# 1D & 2D arrays manual using way
arr8_1 = np.array([1,4,6,])
arr8_2 = np.array([3,9,2,])
arr8_3 = np.array([[0,4,9,2],[3,1,6,9]])
arr8_4 = np.array([[1,2],[3,4],[3,5],[6,7]])
arr8_4 = arr8_3.T

# randomly creating matrix 
# a = np.random.randint(1,100, size = 9 )
# print(a)

# arr8_1 = a
# arr8_2 = a
# arr8_3 = a.reshape(3,3)
# arr8_4 = a.reshape(3,3)

# dot products
dot_product1 = np.dot(arr8_1,arr8_2)
dot_product2 = np.dot(arr8_3,arr8_4)
print(f" dot product of 1 & 2 :\n {dot_product1}")
print(f" dot product of 1 & 2 :\n {dot_product2}")

# cross products

cross_product1 = np.cross(arr8_1, arr8_2)
print(f" cross product of 1 & 2 :\n {cross_product1}")

 dot product of 1 & 2 :
 51
 dot product of 1 & 2 :
 [[101  76]
 [ 76 127]]
 cross product of 1 & 2 :
 [-46  16  -3]


In [11]:
#cross Product

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
print(f"Array A: {array_a}")
print(f"Array B: {array_b}")
cross_product = np.cross(array_a, array_b)
print(f"\nCross product: {cross_product}")

Array A: [1 2 3]
Array B: [4 5 6]

Cross product: [-3  6 -3]


In [12]:
#Q10 Normalize a 2D dataset using broadcasting (subtract mean, divide by std).

#step 1 : let's create the 2D dataset first 

np.random.seed(1234)                                 # in helps in reproducibility ; the same numbers will be printed in every run 
dataset = np.random.randn(4, 3) * 10 + 50            # 4 samples, 3 features
print("Original dataset (4 samples × 3 features):")
print(dataset)
print(f"Shape: {dataset.shape}")

# Step 2: Calculate mean along columns (axis=0)

mean_values = np.mean(dataset, axis=0)               # computes the mean for each column (feature) across all rows (samples).
print(f"\nMean values (per feature): {mean_values}")
print(f"Mean shape: {mean_values.shape}")

# Step 3: Calculate standard deviation along columns

std_values = np.std(dataset, axis=0)                 # computes the standard deviation for each feature.
print(f"Standard deviation (per feature): {std_values}")
print(f"Std shape: {std_values.shape}")

# Step 4: Normalize using broadcasting

normalized_dataset = (dataset - mean_values) / std_values
print(f"\nNormalized dataset:")
print(normalized_dataset)

# Verify normalization

print(f"\nVerification:")
print(f"New means (should be ~0): {np.mean(normalized_dataset, axis=0)}")
print(f"New std devs (should be ~1): {np.std(normalized_dataset, axis=0)}")

Original dataset (4 samples × 3 features):
[[54.71435164 38.09024305 64.32706968]
 [46.87348104 42.79411267 58.8716294 ]
 [58.59588414 43.63476496 50.15696372]
 [27.57315046 61.50035725 59.91946022]]
Shape: (4, 3)

Mean values (per feature): [46.93921682 46.50486948 58.31878076]
Mean shape: (3,)
Standard deviation (per feature): [11.95177248  8.91175919  5.13766994]
Std shape: (3,)

Normalized dataset:
[[ 0.65054241 -0.94421609  1.16945794]
 [-0.00550009 -0.41638881  0.10760688]
 [ 0.97530867 -0.32205813 -1.5886223 ]
 [-1.62035099  1.68266304  0.31155747]]

Verification:
New means (should be ~0): [ 0.00000000e+00 -5.55111512e-17  1.37390099e-15]
New std devs (should be ~1): [1. 1. 1.]


In [13]:
#Q11 Replace all negative numbers in an array with 0.

mixed_array = np.array([-5, 10, -3, 8, -1, 15, -9, 2, -7, 12])
new_array = mixed_array.copy()
new_array[new_array<0] = 0
print(new_array)

[ 0 10  0  8  0 15  0  2  0 12]


In [21]:
#Q12  Create a 4×4 matrix and swap its first and last row.

matrix_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4×4 matrix:")
print(matrix_4x4)

print(f"\nFirst row (index 0): {matrix_4x4[0]}")
print(f"Last row (index -1): {matrix_4x4[-1]}")

# Step 3: Swap rows using array indexing
matrix_swapped = matrix_4x4.copy()  # Create a copy to preserve original
matrix_swapped[[0, -1]] = matrix_swapped[[-1, 0]]
print(f"\nAfter swapping first and last rows:")
print(matrix_swapped)

# Alternative method using temporary variable

# matrix_alt = matrix_4x4.copy()
# temp = matrix_alt[0].copy()
# matrix_alt[0] = matrix_alt[-1]
# matrix_alt[-1] = temp
# print(matrix_alt)

Original 4×4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First row (index 0): [1 2 3 4]
Last row (index -1): [13 14 15 16]

After swapping first and last rows:
[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [31]:
#Q13. Use fancy indexing to select odd numbers from an array.
arr13 = np.array([1,2,3,4,5,6,7,8,9])
odd_indices = np.where(arr13 %2 != 0)
odd_elements = arr13[odd_indices]
odd_elements

array([1, 3, 5, 7, 9])

In [37]:
# Q14. Stack two arrays vertically and horizontally.

arr14_a = np.array([[3,5],[9,2]])
arr14_b = np.array([[7,2],[12,6]])

v_stack = np.vstack((arr14_a,arr14_b))
h_stack = np.hstack((arr14_a,arr14_b))

print(f"vertical stack \n {v_stack}")
print(f"horizontal stack \n {h_stack}")

vertical stack 
 [[ 3  5]
 [ 9  2]
 [ 7  2]
 [12  6]]
horizontal stack 
 [[ 3  5  7  2]
 [ 9  2 12  6]]
